s = "AkiraChix"
print (s.upper())
print (s.islower())
print(s.title())
print(s.count("i"))
print(s.replace("i", "o"))
print(s)
S = (s.replace("i", "o"))
print(S)
print(s.isnumeric())
print(s.isalpha())
print(s.isalnum())
print(s.isdigit())
print(len(s))
print(s.index("i"))
print(s.find("u"))
print(s[-1])
print(s[0:4])